version: '2.2'
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/arm/node-frontend/Dockerfile
      args:
        vue_app_backend_api_url: '"http://10.3.141.1:8081"'
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "8080:8080"
    links:
      - api_backend:api_backend
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    networks:
      - backend

  api_backend:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./docker/arm/node-backend/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - fridgydatabase:/fridgy-backend/database
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    networks:
      - backend

volumes:
  fridgydatabase:

networks:
  backend:
